### ISSUE TITLE
Old normalisation

### ISSUE THREAD

**Issue by cabrera-ziri** [cconroy20/alf#13]
Hey Charile, I think this version of the getmodel still has the old normalisation that complicates the comparison of the BHB parameters with the ones obtained from CMDs.:

https://github.com/cconroy20/alf/blob/67dfb7a5d46ad5d62b53476e75bcd6037ca3c1d2/src/getmodel.f90#L341

I'm using this in my version of the code:

`spec = spec + fy*tmp`

**Comment by cconroy20** [comment]
I've pushed a new version that has the updated normalization.
